import catalog from '../../data/curated-products.json' with {type: 'json'};

/** Branded storefront image generated by scripts/prepare-curated-product-images.mjs. */
export type CuratedImage = {
  src: string;
  alt: string;
  /** Generation recipe; only the image script reads it. */
  from?: unknown;
};

export type CuratedSpecs = {
  pieces?: number;
  /** [min, max] supplier-estimated build time. */
  buildHours?: number[];
  minAge?: number;
  /** Width × depth × height of the assembled piece. */
  sizeCm?: number[];
  lighting?: string;
};

export type CuratedProduct = {
  handle: string;
  productType: string;
  released: boolean;
  shopifyProductId: string | null;
  shopifyVariantId: string | null;
  shippingProfileId: string | null;
  fulfillmentVerified: boolean;
  supplier: string;
  supplierSku: string;
  /** Short display name; the Shopify title stays the SEO title. */
  name?: string;
  /** Category slug within the product type (e.g. a book nook theme). */
  theme?: string;
  tagline?: string;
  description: string;
  details: string;
  specs?: CuratedSpecs;
  /** Supplier processing estimate shown beside the price. */
  processing?: string;
  shipping: string;
  /** Lanes checked against real supplier quotes; the release gate needs one. */
  verifiedDeliveryCountries: string[];
  /**
   * Owner-approved worldwide delivery (every country the store ships to,
   * UK excepted) beyond the verified lanes — the Shopify profile, not this
   * flag, decides where checkout delivers.
   */
  deliversWorldwide?: boolean;
  images?: CuratedImage[];
  /** Transparent 600 × 750 cut-out of the studio image (the homepage shelf). */
  cutout?: string;
};

export const CURATED_PRODUCTS: readonly CuratedProduct[] = catalog;

/** Every generated image is a 1000 × 1250 (4:5) WebP. */
export const CURATED_IMAGE_SIZE = {width: 1000, height: 1250} as const;
export const CURATED_CUTOUT_SIZE = {width: 600, height: 750} as const;

export function getCuratedProduct(
  handle?: string | null,
  products: readonly CuratedProduct[] = CURATED_PRODUCTS,
) {
  const key = handle?.trim().toLowerCase();
  return products.find((product) => product.handle === key) ?? null;
}

/** A supplier import or a release typo alone cannot make a product sellable. */
export function releasedCuratedProducts(
  products: readonly CuratedProduct[] = CURATED_PRODUCTS,
) {
  return products.filter(
    (product) =>
      product.released &&
      product.shopifyProductId?.startsWith('gid://shopify/Product/') &&
      product.shopifyVariantId?.startsWith('gid://shopify/ProductVariant/') &&
      product.shippingProfileId?.startsWith('gid://shopify/DeliveryProfile/') &&
      product.fulfillmentVerified &&
      Boolean(product.supplierSku) &&
      Boolean(product.shipping) &&
      product.verifiedDeliveryCountries.length > 0,
  );
}

export function releasedCuratedProductTypes(
  products: readonly CuratedProduct[] = CURATED_PRODUCTS,
) {
  return [
    ...new Set(releasedCuratedProducts(products).map((p) => p.productType)),
  ];
}

export function isUnreleasedCuratedHandle(handle?: string | null) {
  const product = getCuratedProduct(handle);
  return Boolean(product && !releasedCuratedProducts().includes(product));
}

type StorefrontImage = {
  altText?: string | null;
  height?: number | null;
  url: string;
  width?: number | null;
};

/**
 * Scene composites (a studio recipe with a generated `background`) are
 * written as lossless WebP so every supplier product pixel is provably
 * unchanged — about 1 MB each. The image script writes a lossy copy beside
 * each one for the storefront to serve; the lossless file stays the record.
 */
export function curatedDisplaySrc(image: CuratedImage) {
  const from = image.from as {background?: unknown} | undefined;
  return from?.background
    ? image.src.replace(/\.webp$/, '.display.webp')
    : image.src;
}

/** The branded image set in Storefront API image shape, or [] if none. */
export function curatedImages(
  handle?: string | null,
  products: readonly CuratedProduct[] = CURATED_PRODUCTS,
): StorefrontImage[] {
  return (getCuratedProduct(handle, products)?.images ?? []).map((image) => ({
    altText: image.alt,
    height: CURATED_IMAGE_SIZE.height,
    url: curatedDisplaySrc(image),
    width: CURATED_IMAGE_SIZE.width,
  }));
}

type ImageCarrier = {
  handle: string;
  featuredImage?: StorefrontImage | null;
  images?: {nodes: StorefrontImage[]};
  galleryImages?: {nodes: StorefrontImage[]};
  cardVariant?: {nodes: Array<{image?: StorefrontImage | null}>};
  variants?: {nodes: Array<{image?: StorefrontImage | null}>};
  selectedOrFirstAvailableVariant?: {image?: StorefrontImage | null} | null;
};

/**
 * Swaps the supplier photographs Shopify returns for the branded set, so
 * every card, gallery and thumbnail shows the same treatment. Products
 * without a branded set pass through untouched.
 */
export function withCuratedImages<T extends ImageCarrier>(
  product: T,
  products: readonly CuratedProduct[] = CURATED_PRODUCTS,
): T {
  const images = curatedImages(product.handle, products);
  if (!images.length) return product;
  const lead = images[0];
  const withLead = <V extends {image?: StorefrontImage | null}>(variant: V) =>
    variant.image ? {...variant, image: lead} : variant;
  return {
    ...product,
    featuredImage: lead,
    images: {...product.images, nodes: images},
    ...(product.galleryImages
      ? {galleryImages: {...product.galleryImages, nodes: images}}
      : {}),
    ...(product.cardVariant
      ? {
          cardVariant: {
            ...product.cardVariant,
            nodes: product.cardVariant.nodes.map(withLead),
          },
        }
      : {}),
    ...(product.variants
      ? {
          variants: {
            ...product.variants,
            nodes: product.variants.nodes.map(withLead),
          },
        }
      : {}),
    ...(product.selectedOrFirstAvailableVariant
      ? {
          selectedOrFirstAvailableVariant: withLead(
            product.selectedOrFirstAvailableVariant,
          ),
        }
      : {}),
  } as T;
}

/** The curated short name ("Twilight Library") or the Shopify title. */
export function curatedDisplayTitle(product: {handle: string; title: string}) {
  return getCuratedProduct(product.handle)?.name ?? product.title;
}

const COUNTRY_NAMES: Record<string, string> = {
  AT: 'Austria',
  BE: 'Belgium',
  CY: 'Cyprus',
  DE: 'Germany',
  ES: 'Spain',
  FR: 'France',
  GR: 'Greece',
  IE: 'Ireland',
  IT: 'Italy',
  NL: 'the Netherlands',
  PT: 'Portugal',
};

/** ['CY', 'DE', 'GR'] → "Cyprus, Germany and Greece". */
export function formatDeliveryCountries(codes: readonly string[]) {
  const names = [...new Set(codes)].map((code) => COUNTRY_NAMES[code] ?? code);
  if (names.length <= 1) return names.join('');
  return `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`;
}

export const WORLDWIDE_DELIVERY = 'worldwide, UK excepted';

/** Reads after "Delivery included": "to Cyprus and Germany" or "worldwide, UK excepted". */
export function deliveryIncludedPhrase(
  codes: readonly string[],
  worldwide = false,
) {
  if (worldwide) return WORLDWIDE_DELIVERY;
  const names = formatDeliveryCountries(codes);
  return names ? `to ${names}` : '';
}
